[package]
name = "num_to_ascii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
paste = "1.0.6"